databases:
  - name: jobtracker-db
    databaseName: jobtracker
    user: jobtracker

services:
  - type: web
    name: jobtracker-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobtracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobtracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
